# Trabalho 01 SCC0650 - Computação Gráfica

**Autor** : Tarcídio Antônio Júnior - 10748347

**Introdução:**

A computação gráfica é uma disciplina da ciência da computação que lida com a geração, manipulação e representação de imagens e objetos visuais por meio de software e hardware. Ela desempenha um papel crucial em várias áreas, incluindo entretenimento, design, engenharia, medicina, educação e muitos outros campos. Neste trabalho, aborda-se algumas de suas bases.

**Objetivos do trabalho:**

Neste trabalho, busca-se sedimentar os seguintes conhecimentos: pipeline gráfico, API OpenGL, sistemas de janelas, primitivas geométricas, transformações geométricas 3D, coordenadas homogêneas, além de malhas e texturas. Para isso, o trabalho importa cinco objetos no formato wavefront (.obj) e suas respectivas texturas, permitindo que o usuário aplique transformações geométricas a partir do teclado.

**Descrição dos comandos:**

* Invocação: os objetos são apresentados de forma individual e acionados por eventos de teclado. Ao pressionar a tecla 1, o objeto 1 deve ser exibido, a tecla 2 para o objeto 2 e assim por diante. Todos partem da origem (0,0,0) e não ultrapassam o limite da janela. 
* Movimentação: as teclas 'a','d','s' e 'w' transladam o objeto para esquerda, direita, cima e baixo respectivamente
* Rotação: as teclas 'LEFT', 'RIGHT', 'UP' e 'DOWN' rotacionam o objeto. Os dois primeiros em relação ao eixo y e os dois últimos em relação ao eixo x. As teclas '+' e '-' rotacionam o objeto no eixo z.
* Escala: as teclas 'z' e 'x' aumenta e diminui respectivamente a escala do objeto
* Textura: a tecla 'p' ativa e desativa a textura
* Magnificação: a tecla 'v' altera entre as técnicas de magnificação linear e nearest

**Ferramentas:**

Para criação deste projeto foi utilizado as seguintes ferramentas:
* Linguagem Python
* Sistemas de janela GLFW
* API OpenGL
* Bibliotecas: numpy, math e PIL

---

<sup>Instituto de Ciências Matemáticas e de Computação (ICMC) - Universidade de São Paulo (USP)</sup>

In [25]:
# Duvidas: 
    # Necessiade de controlar a questão das bordas com combinação de transformações?
    # Precisa fazer um .py ou .ipynb?
    # Pode deixar o pip ou pedir para instalar o proprio usuário?
# A fazeres:
    # Fazer read me
    # Fazer video
    # Tratar a combinação de borda 

## Código pré loop principal

### Inicialização do glfw e criação da janela

In [26]:
# Bibliotecas
try: # Importa
    import glfw
    from OpenGL.GL import *
    import numpy as np
    import math
    from PIL import Image
except ImportError: # Caso não importe, instale
    !pip install glfw
    !pip install pyopengl
    !pip install numpy
    !pip install pillow
    import glfw
    from OpenGL.GL import *
    import numpy as np
    import math
    from PIL import Image

# Inicializando sistema glfw
glfw.init()
glfw.window_hint(glfw.VISIBLE, glfw.FALSE)

#get_dim_pos: retorna tamanho da tela e posição da tela
# Entrada: porcentagem largura e altura da tela que deve ser ocupada
# Saída: tamanho da largura e altura da tela, além da posição x e y da tela
def get_dim_pos(per_width = 0.6, per_height = 0.6): 
    # Obtendo configurações do monitor
    monitores = glfw.get_monitors()
    monitor = monitores[0]
    video_mode = glfw.get_video_mode(monitor)
    WIDTH_WINDOW, HEIGHT_WINDOW = video_mode.size
    # Definindo proporção que se quer do monitor
    WIDTH_WINDOW : int = int(per_width*WIDTH_WINDOW)
    HEIGHT_WINDOW : int = int(per_height*HEIGHT_WINDOW)
    POSX_WINDOW : int = (video_mode.size[0] - WIDTH_WINDOW) // 2
    POSY_WINDOW : int = (video_mode.size[1] - HEIGHT_WINDOW) // 2
    return WIDTH_WINDOW, HEIGHT_WINDOW, POSX_WINDOW, POSY_WINDOW

# Pega tamanho da tela e posição da tela
WIDTH_WINDOW, HEIGHT_WINDOW, POSX_WINDOW, POSY_WINDOW = get_dim_pos(0.6,0.6)
# Criando janela
TITLE: str = "Exercício de Malhas"
window = glfw.create_window(WIDTH_WINDOW, HEIGHT_WINDOW, TITLE, None, None)
# Posicionando janela
glfw.set_window_pos(window, POSX_WINDOW, POSY_WINDOW)
glfw.make_context_current(window)

### Criando shaders: Vertex e Fragment

In [27]:
# GLSL para Vertex Shader
vertex_code = """
        attribute vec3 position;
        uniform mat4 mat_pre_transl;
        uniform mat4 mat_rot_x;
        uniform mat4 mat_rot_y;
        uniform mat4 mat_rot_z; 
        uniform mat4 mat_scale;  
        uniform mat4 mat_transl; 

        attribute vec2 texture_coord;
        varying vec2 out_texture;

        void main(){
            gl_Position = mat_transl * mat_scale * mat_rot_x * mat_rot_y * mat_rot_z * mat_pre_transl * vec4(position,1.0);
            out_texture = vec2(texture_coord);
        }
        """

# GLSL para Fragment Shader
fragment_code = """
        uniform vec4 color;
        varying vec2 out_texture;
        uniform sampler2D samplerTexture;
        
        void main(){
            vec4 texture = texture2D(samplerTexture, out_texture);
            gl_FragColor = texture;
        }
        """

### Solicitando espaço, compilando e linkando shaders

In [28]:
# Requisitando slot para GPU
program  = glCreateProgram()
vertex   = glCreateShader(GL_VERTEX_SHADER)
fragment = glCreateShader(GL_FRAGMENT_SHADER)

# Associando os códigos aos espaços
glShaderSource(vertex, vertex_code)
glShaderSource(fragment, fragment_code)

# Compilando shader de vértice
glCompileShader(vertex)
if not glGetShaderiv(vertex, GL_COMPILE_STATUS):
    error = glGetShaderInfoLog(vertex).decode()
    print(error)
    raise RuntimeError("Erro de compilacao do Vertex Shader")

# Compilando shader de fragmento
glCompileShader(fragment)
if not glGetShaderiv(fragment, GL_COMPILE_STATUS):
    error = glGetShaderInfoLog(fragment).decode()
    print(error)
    raise RuntimeError("Erro de compilacao do Fragment Shader")

# Associadno programas compilados ao programa principal
glAttachShader(program, vertex)
glAttachShader(program, fragment)

# Linkagem do programa
glLinkProgram(program)
if not glGetProgramiv(program, GL_LINK_STATUS):
    print(glGetProgramInfoLog(program))
    raise RuntimeError('Linking error')
    
# Tornando programa o atual
glUseProgram(program)

### Definindo classes para objetos do cenário

In [29]:
# graphic_element: classe para criação de elementos que se movimentam no cenário
# Esta classe é genérica, sendo utilizada principalmente para objetos criados pelo próprio programador
class graphic_element:
    def __init__(   self, 
                    inicial_vert = 0, num_vert = 0, 
                    pos_x = 0, pos_y = 0, pos_z = 0,
                    angle_x = 0, angle_y = 0, angle_z = 0,
                    scale = 1,
                    linear_speed = 0.05, angular_speed = 0.139, scale_speed = 0.2,
                    limit_sup = 1,
                    limit_inf = -1):
        # Atributos de identificação
        # Inicialmente estes atributos são inicializados com valores falsos, mas são alterados em seguida
        self._inicial_vert = inicial_vert   # Vértice inicial da onde deve partir a diretiva geométrica
        self._num_vert = num_vert           # Quantidade de vértices que o polígono tem
        # Mapa de eixo
        self.map_eixo = {}
        self.map_eixo['x'] = 0
        self.map_eixo['y'] = 1
        self.map_eixo['z'] = 2
        # Atributos de posição
        self._pos = [pos_x, pos_y, pos_z]   # Posição "central"
        self._linear_speed = linear_speed   # Velocidade do objeto para qualquer eixo
        self._limit_sup = limit_sup         # Limite superior dos dois eixos
        self._limit_inf = limit_inf         # Limite inferior dos dois eixos
        # Atributos de rotação
        self._angle = [angle_x, angle_y, angle_z]
        self._angular_speed = angular_speed
        self._cos = [math.cos(angle_x), math.cos(angle_y), math.cos(angle_z)]
        self._sin = [math.sin(angle_x), math.sin(angle_y), math.sin(angle_z)]
        # Atributos de escala
        self._scale = scale
        self._scale_speed = scale_speed
        # Indica quando o objeto está ativado ou não para ser desenhado
        self._on = False
        # Indica ativação ou não da textura do objeto
        self._polygonal_mode = GL_FILL

    # Ativa e desativa a textura do objeto
    def turn_texture(self):
        if self._polygonal_mode == GL_LINE:
            self._polygonal_mode = GL_FILL
        else:
            self._polygonal_mode = GL_LINE

    # Altera valores de idenficação para desenho
    # Entrada: 
        # Vértice inicial da onde deve partir a diretiva geométrica
        # Número de vértices do objeto
    def set_identification(self, inicial_vert, num_vert):
        self._inicial_vert = inicial_vert
        self._num_vert = num_vert
    
    # Calcula a validade da nova escala do objeto com base no limite de borda
    def _verify_limit(self,
                    new_value,
                    old_value,
                    pos = [False, False, False],
                    angle = [False, False, False],
                    scale = False):
        return new_value
    
    # Retorna estado de ativação do objeto
    def get_on(self):
        return self._on

    # Seta true para ativação do objeto
    def set_on(self):
        self._on = True
    
    # Seta off para ativação do objeto
    def set_off(self):
        self._on = False
    
    # Movimenta o objeto
    # Entrada: operação de somar ou subtrair, além do eixo da movimentação
    def move(self, operation, eixo):
        # A combinação da escolha 'somar','subtrair' e eixo gera todas as movimentações
        if self._on: # Se o objeto estiver ativo
            new_pos = old_pos = self._pos[self.map_eixo[eixo]]
            # Calcula a nova posição
            if operation == '+':
                new_pos += self._linear_speed
            elif operation == '-':
                new_pos -= self._linear_speed
            # Verifica se ela é válida e atribui
            pos_flag = [False, False, False]
            pos_flag[self.map_eixo[eixo]] = True
            if self._verify_limit(new_pos, old_pos, pos = pos_flag):
                self._pos[self.map_eixo[eixo]] = new_pos

    # Rotaciona o objeto
    # Entrada: operação de somar ou subtrair, além do eixo da rotação
    def rotate(self, operation, eixo):
        # A combinação da escolha 'somar','subtrair' e eixo gera todas as rotações
        if self._on:
            new_angle = old_angle = self._angle[self.map_eixo[eixo]]
            # Calcula o novo ângulo
            if operation == '+':
                new_angle += self._angular_speed
            elif operation == '-':
                new_angle -= self._angular_speed
            angle_flag = [False, False, False]
            angle_flag[self.map_eixo[eixo]] = True
            if self._verify_limit(new_angle, old_angle, angle = angle_flag):
                self._angle[self.map_eixo[eixo]] = new_angle
                self._cos[self.map_eixo[eixo]] = math.cos(new_angle)
                self._sin[self.map_eixo[eixo]] = math.sin(new_angle)

    # Escala o objeto
    # Entrada: operação de somar ou subtrair
    def distort(self, operation):
        if self._on:
            # Calcula a nova escala
            new_scale = old_scale = self._scale
            if operation == '+':
                new_scale += self._scale_speed
            elif operation == '-':
                new_scale -= self._scale_speed
            # Verifica se ela é válida e atribui
            if self._verify_limit(new_scale, old_scale, scale = True):
                self._scale = new_scale
    
    # Retorna a matriz de translação do objeto
    def _mat_translation(self):
        return np.array([   1.0, 0.0, 0.0, self._pos[0], 
                            0.0, 1.0, 0.0, self._pos[1], 
                            0.0, 0.0, 1.0, self._pos[2], 
                            0.0, 0.0, 0.0,        1.0], np.float32)
    
    # Retorna a matriz de escala do objeto
    def _mat_scale(self):
        return np.array([     self._scale,           0.0,           0.0, 0.0, 
                                      0.0,   self._scale,           0.0, 0.0, 
                                      0.0,           0.0,   self._scale, 0.0, 
                                      0.0,           0.0,           0.0, 1.0], np.float32)
    
    # Retorna a matriz de rotação no eixo z do objeto
    def _rotation_z(self):  
        return np.array([   self._cos[2], -self._sin[2], 0.0, 0.0, 
                            self._sin[2],  self._cos[2], 0.0, 0.0, 
                                     0.0,           0.0, 1.0, 0.0, 
                                     0.0,           0.0, 0.0, 1.0], np.float32)
    
    # Retorna a matriz de rotação no eixo x do objeto
    def _rotation_x(self): 
        return np.array([   1.0,          0.0,           0.0, 0.0, 
                            0.0, self._cos[0], -self._sin[0], 0.0, 
                            0.0, self._sin[0],  self._cos[0], 0.0, 
                            0.0,          0.0,           0.0, 1.0], np.float32)
    
    # Retorna a matriz de rotação no eixo y do objeto
    def _rotation_y(self):
        return np.array([    self._cos[1],  0.0, self._sin[1], 0.0, 
                                      0.0,  1.0,          0.0, 0.0, 
                            -self._sin[1],  0.0, self._cos[1], 0.0, 
                                      0.0,  0.0,          0.0, 1.0], np.float32)
    # Desenha o objeto na tela
    # Entrada: localizações dos qualificadores uniformes no shader relativos as matrizes de transformação geométrica
    def draw(self, loc_mat_pre_transl, loc_mat_rot_x, loc_mat_rot_y, loc_mat_rot_z, loc__mat_scale, loc_mat_transl, gl_Draw = GL_TRUE):
        if self._on:
            # Define se será mostrado a textura ou não
            glPolygonMode(GL_FRONT_AND_BACK, self._polygonal_mode)
            # Envia as matrizes de transformação
            glUniformMatrix4fv(loc_mat_pre_transl, 1, gl_Draw, np.identity(4)) 
            glUniformMatrix4fv(loc_mat_rot_x, 1, gl_Draw, self._rotation_x()) 
            glUniformMatrix4fv(loc_mat_rot_y, 1, gl_Draw, self._rotation_y()) 
            glUniformMatrix4fv(loc_mat_rot_z, 1, gl_Draw, self._rotation_z()) 
            glUniformMatrix4fv(loc__mat_scale, 1, gl_Draw, self._mat_scale()) 
            glUniformMatrix4fv(loc_mat_transl, 1, gl_Draw, self._mat_translation()) 
            # Desenha o objeto com primitiva GL_TRIANGLES
            glDrawArrays(GL_TRIANGLES, self._inicial_vert, self._num_vert)

In [30]:
# obj_wave: classe para criação de objetos com textura importados
    # Esta classe é específica para objetos importados de wavefront
    # É filha da classe graphic_element
class obj_wave(graphic_element):
    def __init__(   self, 
                    id_texture, path_obj, path_jpg,
                    inicial_vert = 0, num_vert = 0,
                    pos_x = 0, pos_y = 0, pos_z = 0,
                    angle_x = 0, angle_y = 0, angle_z = 0,
                    scale = 1,
                    linear_speed = 0.05, angular_speed = 0.139, scale_speed = 0.2,
                    limit_sup = 1,
                    limit_inf = -1,
                    mag = GL_LINEAR,
                ):
        # Inicializa atributos da mãe
        super().__init__(   inicial_vert = inicial_vert, 
                            num_vert = num_vert,
                            pos_x = pos_x, pos_y = pos_y, pos_z = pos_z,
                            angle_x = angle_x, angle_y = angle_y, angle_z = angle_z,
                            scale = scale,
                            linear_speed = linear_speed, angular_speed = angular_speed, scale_speed = scale_speed,
                            limit_sup = limit_sup,
                            limit_inf = limit_inf
                        )
        # Atributos de identificação
        self._id_texture = id_texture   # id que identifica qual textura se está trabalhando
        self._path_obj = path_obj       # Caminho do arquivo .obj com malhas
        self._path_jpg = path_jpg       # Caminho do arquivo .jpg com texturas
        # Gerando modelos
        # Carregando os valores das coordenadas de maior e menor valor de cada eixo
        # Carregando valores médios de cada coordenada
        self._model, self._min_coord, self._max_coord, self._min_value_coord, self._max_value_coord, self._average_coord = self._load_model_from_file()
        # Encontra a maior diferença entre as coordenadas do objeto
        self._max_dif = self.find_max_dif()
        # Corrigindo escala para limita entre [-1,1]
        self._correct_scale = 1/(2*self._max_dif)
        self._scale = self._scale * self._correct_scale
        self._scale_speed *= self._correct_scale
        # Variável de magnificação que define se será linear ou nearest
        self._mag = mag
        # Carrega textura
        self._load_texture_from_file()
    
    # Alterna entre os modos de magnificação
    def turn_mag(self):
        if self._mag == GL_NEAREST:
            self._mag = GL_LINEAR
            self._load_texture_from_file()
        else:
            self._mag = GL_NEAREST
            self._load_texture_from_file()

    # Encontra a maior diferença entre as coordenadas do objeto
    def find_max_dif(self):
        max_dif = -1
        for i in range(0,3):
            max_dif = max(max_dif, abs(self._min_value_coord[i] - self._max_value_coord[i]))
        return max_dif

    # Calcula a posição final de uma coordenada fornecida
    def _calc_mat_pos_final(self, coord):
        pos_final = np.dot(self._mat_pre_translation().reshape(4,4), coord)
        pos_final = np.dot(self._rotation_z().reshape(4,4), pos_final)
        pos_final = np.dot(self._rotation_y().reshape(4,4), pos_final)
        pos_final = np.dot(self._rotation_x().reshape(4,4), pos_final)
        pos_final = np.dot(self._mat_scale().reshape(4,4), pos_final)
        return np.dot(self._mat_translation().reshape(4,4), pos_final)
    
    # Verifica se com a mudança de um atributo para o novo valor faz com que o objeto saida tela
    # Entrada: novo e antigo valor e flags indicando qual atributo está sendo alterado
    def _verify_limit(self,
                    new_value,
                    old_value,
                    pos = [False, False, False],
                    angle = [False, False, False],
                    scale = False): 
        # Atribui o novo valor ao atributo do objeto temporariamente
        if scale: self._scale = new_value         
        for i in range(0,3):
            if pos[i]: self._pos[i] = new_value
            if angle[i]: 
                self._cos[i] = math.cos(new_value)
                self._sin[i] = math.sin(new_value)
        # Calcula a posições máximas e minimas
        pos_max_min = []
        for i in range(0,3):
            max_coord_temp = np.array(self._max_coord[i] + [float(1)]).reshape(4,1)
            min_coord_temp = np.array(self._min_coord[i] + [float(1)]).reshape(4,1)
            print(max_coord_temp)
            print(min_coord_temp)
            print(self._rotation_z().reshape(4,4))
            pos_max_min.append( self._calc_mat_pos_final(max_coord_temp)  )
            pos_max_min.append( self._calc_mat_pos_final(min_coord_temp) )
        # Retorna o valor antigo ao atributo do objeto
        if scale: self._scale = old_value   
        for i in range(0,3):
            if pos[i]: self._pos[i] = old_value
            if angle[i]: 
                self._cos[i] = math.cos(new_value)
                self._sin[i] = math.sin(new_value)
        print(f'Valor max_min final: {pos_max_min}')
        # Verifica se a posição do máxima e mínima são aceitáveis
        for i in range(0,6):
            if (   pos_max_min[i][0] > self._limit_sup
                or pos_max_min[i][0] < self._limit_inf
                or pos_max_min[i][1] > self._limit_sup
                or pos_max_min[i][1] < self._limit_inf
                or pos_max_min[i][2] > self._limit_sup
                or pos_max_min[i][2] < self._limit_inf
                ):
                return False
        # Se fo, retorna true
        return True

    # Overriding: alterando a forma como o objeto deve se manter ativo
    def set_on(self, id):
        if id == self._id_texture:
            self._on = True
        else:
            self._on = False

    # Função: carrega o arquivo Wavefront
    # Entrada: nome do arquivo
    # Saida: estrutura que armazena o elemento (vertices, textura e faces)
    def _load_model_from_file(self):
        vertices = []
        texture_coords = []
        faces = []
        # Soma das coordenadas para média com intenção de centralizar posição
        sum_coord = [0, 0, 0]
        num_vertices = 0
        # Menor valor de cada eixo
        min_value_coord = [0x3f3f3f3f,0x3f3f3f3f,0x3f3f3f3f]
        min_coord = [[0x3f3f3f3f,0x3f3f3f3f,0x3f3f3f3f], 
                     [0x3f3f3f3f,0x3f3f3f3f,0x3f3f3f3f],
                     [0x3f3f3f3f,0x3f3f3f3f,0x3f3f3f3f]]
        # Maior valor de cada eixo
        max_value_coord = [-0x3f3f3f3f,-0x3f3f3f3f,-0x3f3f3f3f]
        max_coord = [[-0x3f3f3f3f,-0x3f3f3f3f,-0x3f3f3f3f],
                     [-0x3f3f3f3f,-0x3f3f3f3f,-0x3f3f3f3f],
                     [-0x3f3f3f3f,-0x3f3f3f3f,-0x3f3f3f3f]]

        material = None

        # Abre o arquivo obj (wavefront) para leitura
        for line in open(self._path_obj, "r"): ## para cada linha do arquivo .obj
            # Se for comentário, ignore esta linha e use a próxima
            if line.startswith('#'): continue

            # Quebra a linha por espaço
            values = line.split()
            # Se não há informações na linha, ignore esta linha e use a próxima
            if not values: continue

            # Recupera as informações
            ### Armazena coordenadas dos vertices do elemento no vetor vertices
            if values[0] == 'v':
                vertices.append(values[1:4])
                # Se alguma coordenada é maior que todas as outras
                for i in range(1,4):
                    if float(values[i]) > float(max_value_coord[i - 1]):
                        max_value_coord[i - 1] = float(values[i])
                        max_coord[i - 1] = [float(valor) for valor in values[1:4]]
                    if float(values[i]) < float(min_value_coord[i - 1]):
                        min_value_coord[i - 1] = float(values[i])
                        min_coord[i - 1] = [float(valor) for valor in values[1:4]]
                    sum_coord[i - 1] += float(values[i])
                # Somando coordenadas para fazer média
                num_vertices = num_vertices + 1
            ### Armazena coordenadas das texturas no vetor texture_coords
            elif values[0] == 'vt':
                texture_coords.append(values[1:3])
            ### Define o material 
            elif values[0] in ('usemtl', 'usemat'):
                material = values[1]
            ### Armazena informações sobre a construção das faces
            elif values[0] == 'f':
                face = []
                face_texture = []
                # Para cada elemento da linha que define a função
                for bloco in values[1:]:
                    # Separa o elemento em vetor de elementos separando os números que são separados por /
                    positions = bloco.split('/')
                    # Adiciona o primeiro número na face (que representa o número da linha que encontra-se um vértice para da figura)
                    face.append(int(positions[0]))
                    # Se o vetor com elementos separados por / for maior ou igual que dois
                    # Se o segundo número do elemento for maior do que zero
                    if len(positions) >= 2 and len(positions[1]) > 0:
                        # Adicione o segundo número na face de textura (que representa o número da linha que encontra-se um vértice de textura da figura)
                        face_texture.append(int(positions[1]))
                    else:
                        # Se não for maior ou igual a dois ou não for maior que zero, coloque zero na textura
                        face_texture.append(0)
                # Após conseguir, provavelmente, os três valores para face, os três valores para textura e o tipo de material, insira na faces
                faces.append((face, face_texture, material))

        model = {}
        model['vertices'] = vertices
        model['texture'] = texture_coords
        model['faces'] = faces

        return model, min_coord, max_coord, min_value_coord, max_value_coord, sum_coord/np.full(3,num_vertices)
    
    # Função: associa id com a textura
    # Entradas: o id que queremos associar e o caminho do arquivo .jpg
    # Saida: não possui, apenas associa
    def _load_texture_from_file(self):
        #Definindo o id
        glBindTexture(GL_TEXTURE_2D, self._id_texture)
        #Alterando configurações paramétricas de textura
        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_REPEAT)
        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_REPEAT)
        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR)
        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, self._mag)
        #Abre imagem
        img = Image.open(self._path_jpg)
        #Captura as dimensões
        img_width = img.size[0]
        img_height = img.size[1]
        #Transforma imagem para um sequência de bytes em formato raw de arquivo
        image_data = img.tobytes("raw", "RGB", 0, -1)
        #Carregando os dados da imagem
        glTexImage2D(GL_TEXTURE_2D, 0, GL_RGB, img_width, img_height, 0, GL_RGB, GL_UNSIGNED_BYTE, image_data)

    # Função: retorna uma lista com coordenadas dos vertices do objeto e outra com as da textura
    # Obs: como as listas de vértices só tem funcionalidade no momento em que são enviados para a GPU,
        # não há necessidade de manter dentro da classe
    def get_vertices_textures(self):
        vertices_list = []    
        textures_coord_list = []
        # Para cada um das faces (num_line(v), num_line(vt), material)
        for face in self._model['faces']:
            # Para cada um dos números que representa a linha do vértice
            for vertice_id in face[0]: # Pega o valor a coordenada do vértice
                vertices_list.append( self._model['vertices'][vertice_id-1] )
            # Para cada um dos números que representa a linha da coordenada da textura
            for texture_id in face[1]:  # Pega o valor a coordenada da textura
                textures_coord_list.append( self._model['texture'][texture_id-1] )
        return vertices_list, textures_coord_list
    
    # Retorna matriz de translação inicial para garantir que o objeto inicialize em (0,0,0)
    def _mat_pre_translation(self):
        return np.array([   1.0, 0.0, 0.0, - self._average_coord[0], 
                            0.0, 1.0, 0.0, - self._average_coord[1], 
                            0.0, 0.0, 1.0, - self._average_coord[2], 
                            0.0, 0.0, 0.0,                     1.0], np.float32)
    
    # Overriding: altera a maneira de desenhar levando em conta a textura e a translação inicial
    def draw(self, loc_mat_pre_transl, loc_mat_rot_x, loc_mat_rot_y, loc_mat_rot_z, loc_mat_scale, loc_mat_transl, gl_Draw = GL_TRUE):
        if self._on:
            # Define se será utilizado texturas ou não
            glPolygonMode(GL_FRONT_AND_BACK, self._polygonal_mode)
            # Exporta matrizes
            glUniformMatrix4fv(loc_mat_pre_transl, 1, gl_Draw, self._mat_pre_translation())
            glUniformMatrix4fv(loc_mat_rot_x, 1, gl_Draw, self._rotation_x()) 
            glUniformMatrix4fv(loc_mat_rot_y, 1, gl_Draw, self._rotation_y()) 
            glUniformMatrix4fv(loc_mat_rot_z, 1, gl_Draw, self._rotation_z()) 
            glUniformMatrix4fv(loc_mat_scale, 1, gl_Draw, self._mat_scale()) 
            glUniformMatrix4fv(loc_mat_transl, 1, gl_Draw, self._mat_translation())
            # Ativa textura com id
            glBindTexture(GL_TEXTURE_2D, self._id_texture)
            # Desenha o elemento
            glDrawArrays(GL_TRIANGLES, self._inicial_vert, self._num_vert)

### Carregando os modelos

In [31]:
#Ativando texturas 2D
glEnable(GL_TEXTURE_2D)

#Gerando ids
num_textures = 10
textures = glGenTextures(num_textures)

#Carregando modelos
path_wave = 'objetos_wavefront'
# Os nomes devem ser iguais a da pasta
names_obj = ['gato', 'dog', 'pug', 'tigre', 'lobo']
id_obj = 0
objs_wave = []
for name_obj in names_obj:
    path_obj = f'{path_wave}\{name_obj}\{name_obj}.obj'
    path_jpg = f'{path_wave}\{name_obj}\{name_obj}.jpg'
    id_obj = id_obj + 1
    objs_wave.append(obj_wave(id_obj, path_obj, path_jpg))

### Construção dos vetores de dados

In [32]:
# Quantidade total de vértices de objeto a serem utilizados neste programa
total_len_vert_obj = 0
# Quantidade total de vértices de textura a serem utilizados neste programa
total_len_vert_text = 0
# Vértices de objeto a serem utilizados neste programa
vertices_obj_total = []
# Vértices de textura a serem utilizados neste programa
vertices_text_total = []
# Controla os valores que definem a identificação de cada objeto
identification = []

# Para cada objeto:
for obj in objs_wave:
    # Captura os vertices do objeto e de textura
    vertices_list, textures_coord_list = obj.get_vertices_textures()
    # Declara a identificação
    identification.append((total_len_vert_obj, len(vertices_list)))
    # Adiciona o tamanho total dos vertices de objeto e de textura
    total_len_vert_obj += len(vertices_list)
    total_len_vert_text += len(textures_coord_list)
    # Adiciona os vértices de objeto e de textura
    vertices_obj_total += vertices_list
    vertices_text_total += textures_coord_list

#Finaliza a modelagem dos dados de vértices
vertices = np.zeros(total_len_vert_obj, [("position", np.float32, 3)])
vertices['position'] = vertices_obj_total

#Finaliza a modelagem dos dados de texturas
textures = np.zeros(total_len_vert_text, [("position", np.float32, 2)])
textures['position'] = vertices_text_total

#Setando as identificações de desenho do objeto
for i, obj in enumerate(objs_wave):
    obj.set_identification(identification[i][0], identification[i][1])

### Manipulação dos espaços de dados

In [33]:
#Solicita dois buffers para GPU
buffer = glGenBuffers(2)

# Enviando dados de vértice
#Tornando o buffer o buffer padrão de dados
glBindBuffer(GL_ARRAY_BUFFER, buffer[0])
#Subindo os dados de vértice para o buffer na GPU
glBufferData(GL_ARRAY_BUFFER, vertices.nbytes, vertices, GL_STATIC_DRAW)
#Encontrando informações de stride e offset dos vértices
stride = vertices.strides[0]
offset = ctypes.c_void_p(0)
#Capturando posição do atributo "position" e habilitando
loc_vertices = glGetAttribLocation(program, "position")
glEnableVertexAttribArray(loc_vertices)
#Linkando dados ao atributo "position"
glVertexAttribPointer(loc_vertices, 3, GL_FLOAT, False, stride, offset)

# Enviando dados de textura
#Tornando o buffer o buffer padrão de dados
glBindBuffer(GL_ARRAY_BUFFER, buffer[1])
#Subindo os dados de textura para o buffer na GPU
glBufferData(GL_ARRAY_BUFFER, textures.nbytes, textures, GL_STATIC_DRAW)
#Encontrando informações de stride e offset das texturas
stride = textures.strides[0]
offset = ctypes.c_void_p(0)
#Capturando posição do atributo "texture_coord" e habilitando
loc_texture_coord = glGetAttribLocation(program, "texture_coord")
glEnableVertexAttribArray(loc_texture_coord)
#Linkando dados ao atributo "texture_coord"
glVertexAttribPointer(loc_texture_coord, 2, GL_FLOAT, False, stride, offset)

# Capturando posição dos uniform "mat_rot_x, mat_rot_y, mat_rot_z, mat_scale, mat_transl e mat_pre_transl"
loc_mat_rot_x = glGetUniformLocation(program, "mat_rot_x")
loc_mat_rot_y = glGetUniformLocation(program, "mat_rot_y")
loc_mat_rot_z = glGetUniformLocation(program, "mat_rot_z")
loc_mat_scale = glGetUniformLocation(program, "mat_scale")
loc_mat_transl = glGetUniformLocation(program, "mat_transl")
loc_mat_pre_transl = glGetUniformLocation(program, "mat_pre_transl")

### Eventos de teclado e mouse

In [34]:
# Define um objeto principal para uso na capturação de eventos
main_obj = objs_wave[0]
# Controladores de teclas para evitar erro
press_keys = [True, True]

def key_event(window,key,scancode,action,mods):
    global objs_wave, main_obj, press_keys

    # Ativando objetos
    # Determinando id_obj
    id_obj = key

    # Ativa o objeto chamado
    if id_obj >= 48 and id_obj <= 57:
        id_obj = id_obj - 48
        # Ativa e desativa objeto
        for obj in objs_wave:
            obj.set_on(id_obj)
            if obj.get_on():
                main_obj = obj # Apenas por otimização, captura o objeto ativo
    
    # Ações do objeto
    if key == 262: main_obj.rotate('-', 'y')    #Tecla LEFT: rotacionar para esquerda
    if key == 263: main_obj.rotate('+','y')     #Tecla RIGHT: rotacionar para direita
    
    if key == 264: main_obj.rotate('-','x')     #Tecla DOWN: rotacionar para baixo
    if key == 265: main_obj.rotate('+','x')     #Tecla UP: rotacionar para cima

    if key == 333: main_obj.rotate('-','z')     #Tecla -: rotacionar no sentido antihorario
    if key == 334: main_obj.rotate('+','z')     #Tecla +: rotacionar no sentido horario

    if key == 88: main_obj.distort('-')         #Tecla X: diminuir escala
    if key == 90: main_obj.distort('+')         #Tecla Z: aumentar escala

    if key == 87: main_obj.move('+','y')        #Tecla W: mover para cima
    if key == 83: main_obj.move('-','y')        #Tecla S: mover para baixo
    if key == 65: main_obj.move('-','x')        #Tecla A: mover para esquerda
    if key == 68: main_obj.move('+','x')        #Tecla D: mover para direita

    if key == 80:                               #Tecla P: altera visualização de textura
        if press_keys[0]:
            main_obj.turn_texture()
            press_keys[0] = False
        else:
            press_keys[0] = True

    if key == 86:                               #Tecla V: altera modo de magnificação
        if press_keys[1]:
            main_obj.turn_mag()
            press_keys[1] = False
        else:
            press_keys[1] = True

    # print('[key event] key=',key)
    # print('[key event] scancode=',scancode)
    # print('[key event] action=',action)
    # print('[key event] mods=',mods)
    # print('-------')

# Seta função de ação de eventos de teclado
glfw.set_key_callback(window,key_event)

# Seta função de ação de eventos de mouse
# def mouse_event(window,button,action,mods):
#     print('[mouse event] button=',button)
#     print('[mouse event] action=',action)
#     print('[mouse event] mods=',mods)
#     print('-------')
    
# glfw.set_mouse_button_callback(window,mouse_event)

### Exibindo na tela

In [35]:
glfw.show_window(window)

## Loop principal

In [36]:
# Habilita 3D
glEnable(GL_DEPTH_TEST)

# Loop principal
while not glfw.window_should_close(window):
    # Lê eventos
    glfw.poll_events()
    # Limpa buffer de cor e Z-buffer
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT)
    # Define cor como sendo RGB(1.0,1.0,1.0)
    glClearColor(1.0, 1.0, 1.0, 1.0)
    
    # Percorre por todos os objetos
    for obj in objs_wave:
        # Se ele estiver ativado (apenas para otimização, refaz a checagem)
        if obj.get_on():
            # Desenha o objeto
            obj.draw(loc_mat_pre_transl, loc_mat_rot_x, loc_mat_rot_y, loc_mat_rot_z, loc_mat_scale, loc_mat_transl)
    
    # Gerencia troca de dados entre janela e OpenGL
    glfw.swap_buffers(window)

# Encerra
glfw.terminate()

[[31.101 ]
 [29.7026]
 [-5.4363]
 [ 1.    ]]
[[-34.5371]
 [ 44.3604]
 [ -0.1143]
 [  1.    ]]
[[ 1. -0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
[[-34.3008]
 [ 45.3063]
 [ -0.1128]
 [  1.    ]]
[[-11.9431]
 [ -0.1019]
 [  6.198 ]
 [  1.    ]]
[[ 1. -0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
[[28.0203]
 [22.6943]
 [ 8.5436]
 [ 1.    ]]
[[-10.6056]
 [  0.7247]
 [ -8.2056]
 [  1.    ]]
[[ 1. -0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
Valor max_min final: [array([[ 0.12624657],
       [ 0.08272857],
       [-0.05487265],
       [ 1.        ]]), array([[-0.37375344],
       [ 0.19892483],
       [-0.03019346],
       [ 1.        ]]), array([[-0.37195342],
       [ 0.20606234],
       [-0.03118047],
       [ 1.        ]]), array([[-0.20164303],
       [-0.12983907],
       [ 0.06435373],
       [ 1.        ]]), array([[0.10277926],
       [0.04461236],
       [0.05798928],
       [1.        ]]), array([[-0.1914